FLT-1235 [VS] Генерация виджетов на основе CoreMwwmWidget
surfstudio/SurfGear pull request #111
Opened 2021-03-18 11:55 UTC by trushchinskii-surf

2021-03-19 07:18 UTC, artem-zaitsev requested changes
Поправь плиз

2021-03-19 07:18 UTC, artem-zaitsev commented on tools/ide/vs_code/extensions/mwwm_generator/src/creators.ts
> +    private async getWidgetName(): Promise<string> {
Этот метод в классе выше вроде есть. В TS нет наследования?

2021-03-19 07:18 UTC, artem-zaitsev commented on tools/ide/vs_code/extensions/mwwm_generator/src/creators.ts
> +    const widgetSourceCode = fs.readFileSync(widgetSourceCodePath, 'utf8').replace(/Template/gi, name);
может пути в константы вынести?

2021-03-19 07:18 UTC, artem-zaitsev commented on tools/ide/vs_code/extensions/mwwm_generator/src/extension.ts
> +		console.log('0');
опять логи

2021-03-19 07:18 UTC, artem-zaitsev commented on tools/ide/vs_code/extensions/mwwm_generator/src/creators.ts
> +    const widgetSourceCode = fs.readFileSync(widgetSourceCodePath, 'utf8').replace(/Template/gi, name);
точнее паттерн для замены

2021-04-02 11:10 UTC, trushchinskii-surf commented on tools/ide/vs_code/extensions/mwwm_generator/src/creators.ts
> +        console.log('2');
+

2021-04-02 11:13 UTC, trushchinskii-surf commented on tools/ide/vs_code/extensions/mwwm_generator/src/creators.ts
> +    private async getWidgetName(): Promise<string> {
+

2021-04-02 11:13 UTC, trushchinskii-surf commented on tools/ide/vs_code/extensions/mwwm_generator/src/extension.ts
> +		console.log('0');
+

2021-04-02 11:14 UTC, trushchinskii-surf commented on tools/ide/vs_code/extensions/mwwm_generator/src/creators.ts
> +    const widgetSourceCode = fs.readFileSync(widgetSourceCodePath, 'utf8').replace(/Template/gi, name);
Не вижу особого смысла

2021-04-02 11:52 UTC, merged