Spo 4579 mwwm todo example
surfstudio/SurfGear pull request #135
Opened 2021-04-13 09:33 UTC by DanilaGogolev

2021-04-13 10:17 UTC, artem-zaitsev requested changes

2021-04-13 10:17 UTC, artem-zaitsev commented on packages/mwwm/example/todos/lib/ui/screens/add_edit_screen/add_edit_screen.dart
> +  static final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
можно его в wm сделать

2021-04-13 10:17 UTC, artem-zaitsev commented on packages/mwwm/example/todos/lib/storage/app_storage.dart
> +class AppStorage {
А какой вообще смысл в AppStorage?

2021-04-13 10:17 UTC, artem-zaitsev commented on packages/mwwm/example/todos/lib/ui/app/app_wm.dart
> +class AppWidgetModel extends WidgetModel {
Она точно нужна?

2021-04-13 15:56 UTC, DanilaGogolev commented on packages/mwwm/example/todos/lib/ui/screens/add_edit_screen/add_edit_screen.dart
> +  static final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
Поправил

2021-04-13 15:57 UTC, DanilaGogolev commented on packages/mwwm/example/todos/lib/ui/app/app_wm.dart
> +class AppWidgetModel extends WidgetModel {
Убрал

2021-04-14 12:29 UTC, artem-zaitsev approved these changes
В целом ок, посмотри пару вопросов

2021-04-14 12:29 UTC, artem-zaitsev commented on examples/todos/lib/repositories/todos_repository.dart
> +  StreamedState<FilterType> get currentFilterState => _currentFilterState;
а смысл в геттерах этих? Все равно поле final, изменить не сможем ссылку.

2021-04-14 12:29 UTC, artem-zaitsev commented on examples/todos/lib/ui/navigation/navigation.dart
> +class Navigation {
Не поверишь, вчера аналогичную штуку в своем проекте сделал)))

2021-04-14 12:29 UTC, artem-zaitsev commented on examples/todos/lib/ui/screens/add_edit_screen/add_edit_screen.dart
> +          _formKey.currentState!.save();
не стал управление в wm уносить? Из-за тестов?

2021-04-14 12:42 UTC, DanilaGogolev commented on examples/todos/lib/ui/screens/add_edit_screen/add_edit_screen.dart
> +          _formKey.currentState!.save();
Верно

2021-04-14 12:48 UTC, DanilaGogolev commented on examples/todos/lib/repositories/todos_repository.dart
> +  StreamedState<FilterType> get currentFilterState => _currentFilterState;
Убрал.

2021-04-15 07:30 UTC, dkrutskikh approved these changes

2021-04-15 07:30 UTC, dkrutskikh commented on examples/todos/lib/ui/screens/add_edit_screen/add_edit_screen.dart
> +  static final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
@DanilaGogolev не вижу смысла в типе у приватного поля

2021-04-15 07:31 UTC, merged