Update surf lint rules
surfstudio/SurfGear pull request #174
Opened 2021-05-17 15:40 UTC by grafovdenis

2021-05-17 15:50 UTC, dkrutskikh requested changes

2021-05-17 15:50 UTC, dkrutskikh commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +include: package:pedantic/analysis_options.1.11.0.yaml
@grafovdenis please use `analysis_options.yaml` instead `analysis_options.1.11.0.yaml`

2021-05-17 15:56 UTC, grafovdenis commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +include: package:pedantic/analysis_options.1.11.0.yaml
fixed

2021-05-18 04:55 UTC, trushchinskii-surf commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_require_non_null_named_parameters: false
А почему тут false? В каких кейсах это мешает?

2021-05-18 04:55 UTC, trushchinskii-surf commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +          - private-methods
Давайте приведем этот список в нашему, который находится в код стайле

2021-05-18 07:42 UTC, artem-zaitsev requested changes

2021-05-18 07:42 UTC, artem-zaitsev commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    sort_constructors_first: false
В чем причина изменения?

2021-05-18 07:42 UTC, artem-zaitsev commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_use_package_imports: false
Почему?

2021-05-18 07:44 UTC, dkrutskikh commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    sort_constructors_first: false
так мы отменили требования писать конструктор первыми

2021-05-18 07:45 UTC, dkrutskikh commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_use_package_imports: false
очень удобно писать

```dart
import 'package:mwwm/mwwm.dart';

import 'signin_screen_i18n.dart';
import 'signin_screen_wm.dart';

class SignInHeader extends StatelessWidget {
```

2021-05-18 08:05 UTC, pretorean commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    sort_constructors_first: false
а почему отменили? кто так решил?

2021-05-18 08:07 UTC, pretorean commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_use_package_imports: false
ты так говоришь, как будто руками импорт пишешь.
какие еще недостатки у полного импорта через package?

2021-05-18 08:07 UTC, dkrutskikh commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    sort_constructors_first: false
наверное большинство, мы читаем офф гайдлайны https://github.com/surfstudio/SurfGear/blob/main/docs/ru/common/code_style.md#%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0

2021-05-18 08:08 UTC, dkrutskikh commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_use_package_imports: false
я пишу руками

2021-05-18 08:08 UTC, dkrutskikh commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_use_package_imports: false
какие минусы в отсутствии написания package?

2021-05-18 09:34 UTC, artem-zaitsev commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_use_package_imports: false
приняли что для единообразия пишем везде package

2021-05-18 09:34 UTC, artem-zaitsev commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_use_package_imports: false
единственное надо посмотреть есть ли разница при написании пакетов(там вроде есть нюанс)

2021-05-18 13:05 UTC, grafovdenis commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_require_non_null_named_parameters: false
Это случайно, поправлю.

2021-05-19 07:55 UTC, dkrutskikh requested changes

2021-05-19 07:55 UTC, dkrutskikh commented on packages/surf_lint_rules/dart_dependency_validator.yaml
> +  - meta
@grafovdenis why we need to ignore this package?

2021-05-19 07:55 UTC, dkrutskikh commented on packages/surf_lint_rules/example/lib/async_function.dart
> +Future<void> asyncFunction() => Future.value();
@grafovdenis please don't forget include our license header

2021-05-19 07:55 UTC, dkrutskikh commented on packages/surf_lint_rules/example/lib/main.dart
> +  // ignore: unused_element
@grafovdenis please use global `// ignore_for_file: unused_element` instead locally ignores

2021-05-19 08:33 UTC, dkrutskikh approved these changes

2021-05-19 08:37 UTC, artem-zaitsev commented on packages/surf_lint_rules/lib/analysis_options.yaml
> +    always_use_package_imports: false
Так что здесь решили? 
Мне видится так: в проектах должен быть package импорт
В модулях/пакетах внутри src - относительный

2021-05-19 08:41 UTC, trushchinskii-surf approved these changes

2021-05-19 09:09 UTC, artem-zaitsev approved these changes

2021-05-19 09:35 UTC, merged