Flt 1288 update readme
surfstudio/SurfGear pull request #177
Opened 2021-05-18 14:16 UTC by dkrutskikh

2021-05-18 14:30 UTC, artem-zaitsev approved these changes

2021-05-18 14:54 UTC, grafovdenis approved these changes

2021-05-18 14:59 UTC, saturov requested changes

2021-05-18 14:59 UTC, saturov commented on README.md
> +* [Virtual Keyboard](#virtual-keyboard)
В общем, нет никакого смысла в сортировке пакетов по алфавиту тут.
Надо, как мы и обсуждали когда-то, выделить несколько категорий пакетов (например "архитектурные", UI и так далее), а затем разбить пакеты на соответствующие разделы здесь. Будет намного удобнее.

2021-05-18 15:06 UTC, dkrutskikh commented
@saturov критерии группировки?

2021-05-19 07:39 UTC, saturov approved these changes

2021-05-19 07:43 UTC, merged