Relation improvements
surfstudio/SurfGear pull request #187
Opened 2021-05-20 08:33 UTC by grafovdenis

* Add the ability to get an error in `EntityStateBuilder` from `errorChild`
* Add data argument to `EntityStreamedState`

2021-05-20 08:39 UTC, dkrutskikh requested changes

2021-05-20 08:39 UTC, dkrutskikh commented on packages/relation/CHANGELOG.md
> +## 1.2.0
@grafovdenis please don't bump package version

2021-05-20 08:39 UTC, dkrutskikh commented on packages/relation/lib/src/builder/entity_state_builder.dart
> +  final ErrorWidgetBuilder? errorBuilder;
@grafovdenis looks like breaking changes, is it true?

2021-05-20 08:39 UTC, dkrutskikh commented on packages/relation/lib/src/builder/entity_state_builder.dart
> +                streamData.error?.e != null
@grafovdenis please extract to variable

2021-05-20 08:39 UTC, dkrutskikh commented on packages/relation/lib/src/builder/entity_state_builder.dart
> +            if (errorBuilder != null) {
@grafovdenis please cover by tests

2021-05-20 09:33 UTC, arefimenko approved these changes

2021-05-20 09:49 UTC, IlyaMax commented on packages/relation/lib/src/builder/entity_state_builder.dart
> +          if (errorDataBuilder != null) {
I think it'd better to add docs about priority of this builders and that errorChild has the lowest one.

2021-05-20 10:06 UTC, grafovdenis commented on packages/relation/lib/src/builder/entity_state_builder.dart
> +              ? streamData.error!.e as Exception
```dart
class ExceptionWrapper {
  const ExceptionWrapper(this.e);

  /// Some exception
  final dynamic e;
}
```

Можно поменять `dynamic` на `Exception`, но мы потеряем возможность пихать туда `Error`.

2021-05-20 10:10 UTC, IlyaMax commented on packages/relation/lib/src/builder/entity_state_builder.dart
> +  final DataWidgetErrorBuilder<T>? errorDataBuilder;
лучше тогда поменять название переменной, правильнее dataerror или даже лучше errorwithdata

2021-05-20 14:25 UTC, dkrutskikh approved these changes

2021-05-21 07:31 UTC, artem-zaitsev approved these changes

2021-05-21 07:31 UTC, merged