LLC-3045 add optional indicator to material swipe refresh
surfstudio/SurfGear pull request #219
Opened 2021-05-27 09:59 UTC by IlyaMax

2021-05-27 10:42 UTC, artem-zaitsev requested changes

2021-05-27 10:42 UTC, artem-zaitsev commented on packages/swipe_refresh/lib/src/custom_refresh_indicator.dart
> +// Copyright 2014 The Flutter Authors. All rights reserved.
А что изменилось в этом файле, что его надо заинуть к нам?

2021-05-27 11:33 UTC, IlyaMax commented on packages/swipe_refresh/lib/src/custom_refresh_indicator.dart
> +// Copyright 2014 The Flutter Authors. All rights reserved.
сейчас напишу коммент

2021-05-27 11:36 UTC, IlyaMax commented on packages/swipe_refresh/lib/src/custom_refresh_indicator.dart
> +// Copyright 2014 The Flutter Authors. All rights reserved.
+

2021-05-27 13:29 UTC, IlyaMax commented
@artem-zaitsev По бампу версии всё ок или не нужно было?

2021-05-27 17:55 UTC, dkrutskikh commented
@IlyaMax не вижу тестов на новый функционал

2021-05-27 17:56 UTC, dkrutskikh requested changes

2021-05-27 17:56 UTC, dkrutskikh commented on packages/swipe_refresh/lib/src/custom_refresh_indicator.dart
> +// Copyright 2014 The Flutter Authors. All rights reserved.
@IlyaMax присоединяюсь к прошлому вопросу, так-же у меня вопрос лицензионности наших действий

2021-05-27 17:56 UTC, dkrutskikh commented on packages/swipe_refresh/lib/src/material_swipe_refresh.dart
>  import 'package:flutter/widgets.dart';
@IlyaMax давай удалим этот import

2021-05-27 17:56 UTC, dkrutskikh commented on packages/swipe_refresh/pubspec.yaml
> +custom:
@IlyaMax зачем этот блок?

2021-05-28 06:29 UTC, trushchinskii-surf approved these changes

2021-05-28 13:59 UTC, artem-zaitsev approved these changes

2021-05-28 13:59 UTC, artem-zaitsev commented on packages/swipe_refresh/lib/src/custom_refresh_indicator.dart
> +// Copyright 2014 The Flutter Authors. All rights reserved.
Вроде с BSD ок все.

С копированием файла я понял. Тоже ок

2021-05-31 10:54 UTC, IlyaMax commented on packages/swipe_refresh/lib/src/material_swipe_refresh.dart
>  import 'package:flutter/widgets.dart';
+

2021-05-31 10:55 UTC, IlyaMax commented on packages/swipe_refresh/pubspec.yaml
> +custom:
прилетел из мейна при мерже, убрал

2021-05-31 13:53 UTC, dkrutskikh requested changes

2021-05-31 13:53 UTC, dkrutskikh commented on packages/swipe_refresh/lib/src/custom_refresh_indicator.dart
> +// Copyright 2014 The Flutter Authors. All rights reserved.
@IlyaMax нам точно нужен весь файл ? Если да - то надо-бы покрыть его полностью тестами и исправить линты, а не исключать его из анализа.

2021-07-07 09:33 UTC, MbIXjkee commented on packages/swipe_refresh/lib/src/custom_refresh_indicator.dart
> +// Copyright 2014 The Flutter Authors. All rights reserved.
Вообще мне кажется тащить к себе кусок фреймворка неправильно, даже если не касаться лицензии - потому что нам нужно будет поддерживать изменения которые в этой части происходят, если есть действительно необходимость в правке какой-то нутрянки, то скорее мы идем неправильным путем. Может стоит поискать другой вариант реализации?

2021-07-08 15:00 UTC, closed without merging