Mwwm better null safety migration
surfstudio/SurfGear pull request #225
Opened 2021-05-31 15:14 UTC by IlyaMax

2021-05-31 15:32 UTC, dkrutskikh requested changes

2021-05-31 15:32 UTC, dkrutskikh commented on packages/mwwm/CHANGELOG.md
> +* Removed nullable types where possible
@IlyaMax looks like Major changes

2021-05-31 15:32 UTC, dkrutskikh commented on packages/mwwm/example/lib/ui/counter_screen/counter_wm.dart
> +  int counter = 0;
@IlyaMax please add blank line

2021-05-31 15:32 UTC, dkrutskikh commented on packages/mwwm/lib/src/widget_model.dart
> +  final _compositeSubscription = CompositeSubscription();
@IlyaMax missed blank lines

2021-05-31 15:32 UTC, dkrutskikh commented on packages/mwwm/lib/src/widget_model.dart
> +          .add<T>(stream.listen(onValue, onError: onError?.call));
@IlyaMax why you add generic type?

2021-05-31 15:32 UTC, dkrutskikh commented on packages/mwwm/test/widget_model_test.dart
> +        // ignore: deprecated_member_use_from_same_package
@IlyaMax you can use ignore_for_file

2021-05-31 15:37 UTC, IlyaMax commented on packages/mwwm/lib/src/widget_model.dart
> +          .add<T>(stream.listen(onValue, onError: onError?.call));
I think it's better to specify it explicitly. In method `subscribeHandleError` it is implemented the same way. `return _compositeSubscription.add<T>(subscription);`

2021-05-31 16:09 UTC, IlyaMax commented on packages/mwwm/test/widget_model_test.dart
> +        // ignore: deprecated_member_use_from_same_package
+

2021-05-31 16:10 UTC, IlyaMax commented on packages/mwwm/example/lib/ui/counter_screen/counter_wm.dart
> +  int counter = 0;
+

2021-05-31 16:10 UTC, IlyaMax commented on packages/mwwm/lib/src/widget_model.dart
> +  final _compositeSubscription = CompositeSubscription();
+

2021-05-31 16:11 UTC, IlyaMax commented on packages/mwwm/CHANGELOG.md
> +* Removed nullable types where possible
+

2021-05-31 19:01 UTC, artem-zaitsev requested changes

2021-05-31 19:01 UTC, artem-zaitsev commented on packages/mwwm/lib/src/widget_state.dart
> +  void dispose() {
place lifecycle methods in order they are calling by framework:
initState -> ... -> dispose

2021-06-01 06:29 UTC, trushchinskii-surf approved these changes

2021-06-01 10:17 UTC, IlyaMax commented on packages/mwwm/lib/src/widget_state.dart
> +  void dispose() {
+

2021-06-01 10:48 UTC, IlyaMax commented
it closes these issues #112 #46

2021-06-01 11:36 UTC, trushchinskii-surf approved these changes

2021-06-01 14:49 UTC, artem-zaitsev approved these changes

2021-06-02 09:02 UTC, artem-zaitsev requested changes

2021-06-02 09:02 UTC, artem-zaitsev commented on packages/mwwm/lib/src/widget_state.dart
> +typedef WidgetModelBuilder<WM> = WM Function(BuildContext context);
Зачем? Здесь не имеет смысла вывод типа.

2021-06-02 12:01 UTC, IlyaMax commented on packages/mwwm/lib/src/widget_state.dart
> +typedef WidgetModelBuilder<WM> = WM Function(BuildContext context);
Имеет. Услышал аргумент от @HazarD2311 что так неудобно/сложно будет подменять WidgetState.  Но на самом деле наоборот. Если подменишь WidgetState который работает с другой вмкой и забудешь поменять конкретную виджет модельку в WidgetModelBuilder получишь ошибку каста в рантайме. Если сделать тут женерик получишь ошибку до компиляции

2021-06-04 07:22 UTC, artem-zaitsev commented on packages/mwwm/lib/src/widget_state.dart
> +typedef WidgetModelBuilder<WM> = WM Function(BuildContext context);
Принято!

2021-06-04 07:26 UTC, artem-zaitsev approved these changes

2021-06-04 07:30 UTC, merged