Old widget state fix
surfstudio/SurfGear pull request #243
Opened 2021-06-09 11:14 UTC by IlyaMax

2021-06-09 11:16 UTC, IlyaMax commented
That's because I changed _ProxyMwwmWidget type from CoreMwwmWidget to StatefulWidget

2021-06-09 11:20 UTC, dkrutskikh requested changes

2021-06-09 11:20 UTC, dkrutskikh commented on packages/surf_mwwm/CHANGELOG.md
> +* OldWidgetState fix
@IlyaMax please provide more detailed log

2021-06-10 14:51 UTC, IlyaMax commented on packages/surf_mwwm/CHANGELOG.md
> +* OldWidgetState fix
+

2021-06-11 12:00 UTC, dkrutskikh approved these changes

2021-06-11 12:00 UTC, merged