Feature/extensions
surfstudio/SurfGear pull request #25
Opened 2020-11-25 13:20 UTC by artem-zaitsev

Набор экстеншенов, которые испольщую на своем пет проекте.

Если понравится предлагаю использовать у нас.

Там есть полезные экстеншены для Future:

```
void someFuncInWm() async {
  var res = await someInteractor.getData().on(this) //without errorHandler
  var res = await someInteractor.getData().withErrorHandling(this) //with errorHandler
}
```

2020-11-25 13:34 UTC, saturov requested changes

2020-11-25 13:34 UTC, saturov commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +extension FutureExt<T> on Future<T> {
Использовать сокращения в нейминге не круто. Было бы здорово так и называть их `{Whatever}Extension`.

2020-11-25 13:34 UTC, saturov commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
>  /// утилиты-расширения для [WidgetModel]
Русскоязычная документация не должна быть в Surf Gear.

2020-11-25 13:34 UTC, saturov commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +extension StreamX<T> on Stream<T> {
Тут вообще с неймингом не задалось :)

2020-11-25 13:34 UTC, saturov commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +            }
Точно потом список стейтов не расширится и тут не случится беды?

2020-11-25 13:34 UTC, saturov commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +  void listenCathError(
Грамматическая ошибка

2020-11-25 13:34 UTC, saturov commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +  void listenCathError(
Грамматическая ошибка

2020-11-25 13:38 UTC, artem-zaitsev commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
>  /// утилиты-расширения для [WidgetModel]
Согласен.

2020-11-25 13:39 UTC, artem-zaitsev commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +extension FutureExt<T> on Future<T> {
Это кстати устаревшая тема. Мне больше нравится FutureX. Что думаешь?

2020-11-25 13:39 UTC, artem-zaitsev commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +            }
Как раз это вопрос доработток)

2020-11-26 08:50 UTC, saturov commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +            }
Просто сейчас сделано так, что об этом не узнаешь, пока не напорешься.

2020-11-26 08:50 UTC, saturov commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +extension FutureExt<T> on Future<T> {
Возможно

2021-01-12 08:39 UTC, pretorean approved these changes

2021-01-28 13:18 UTC, knightsforce commented on packages/surf_mwwm/example/lib/ui/screen/counter/counter_wm.dart
> +    }).listenOn(this);
Зачем нужен listenOn, если есть bind? Как я понял, это нужно для сбора подписки через subscribe. Но тогда мы заменяем простой bind(action, callback) на более странную конструкцию.

2021-01-29 23:21 UTC, artem-zaitsev commented on packages/surf_mwwm/example/lib/ui/screen/counter/counter_wm.dart
> +    }).listenOn(this);
Как минимум, возможен множественный bind. Далее в bind не надо указывать слушателя и можно делать цепочки: bind, потом что-то ещё, и только потом навесить listen

2021-03-15 07:46 UTC, merged