Null safe streamed state builder
surfstudio/SurfGear pull request #252
Opened 2021-06-17 15:23 UTC by IlyaMax

2021-06-17 15:28 UTC, IlyaMax commented
This closes #217

2021-06-18 10:57 UTC, dkrutskikh requested changes

2021-06-18 10:57 UTC, dkrutskikh commented on packages/relation/example/lib/demo_relations.dart
>    Future _load() async {
@IlyaMax please change type to Future<void>

2021-06-18 10:57 UTC, dkrutskikh commented on packages/relation/test/builder/streamed_state_builder_test.dart
> +      await tester.pumpWidget(makeTestableWidget(streamedStateBuilder));
@IlyaMax you can use pumpWidgetBuilder without custom wrapper

2021-06-18 10:57 UTC, dkrutskikh commented on packages/relation/test/builder/streamed_state_builder_test.dart
> +    'StreamedStateBuilder nullable test',
@IlyaMax please wrap these tests in group

2021-06-19 10:26 UTC, IlyaMax commented on packages/relation/test/builder/streamed_state_builder_test.dart
> +      await tester.pumpWidget(makeTestableWidget(streamedStateBuilder));
I can't find this method. Please give me more detailed info what should I use.

2021-06-19 12:03 UTC, IlyaMax commented on packages/relation/test/builder/streamed_state_builder_test.dart
> +    'StreamedStateBuilder nullable test',
+

2021-06-19 12:05 UTC, dkrutskikh approved these changes

2021-06-21 08:49 UTC, trushchinskii-surf approved these changes

2021-06-21 09:13 UTC, artem-zaitsev approved these changes

2021-06-21 09:14 UTC, merged