SPO-5955-added-example
surfstudio/SurfGear pull request #253
Opened 2021-06-18 09:55 UTC by plastb1r

2021-06-18 10:01 UTC, IlyaMax commented
Нужно будет когда закроют #252 обновить пример чтобы не было косяков

2021-06-18 10:48 UTC, dkrutskikh requested changes

2021-06-18 10:48 UTC, dkrutskikh commented on examples/simple_messenger/pubspec.yaml
> +  relation: ^4.0.0-dev.1
@plastb1r тут лучше подключить 3ю мажорку

2021-06-18 10:48 UTC, dkrutskikh commented on examples/simple_messenger/analysis_options.yaml
> +# Customizing static analysis
@plastb1r почему не воспользовался пакетом surf_lint_rules?

2021-06-18 11:43 UTC, plastb1r commented on examples/simple_messenger/analysis_options.yaml
> +# Customizing static analysis
@dkrutskikh  через пакет линты долго не хотели запускаться и решил пока простым файлом добавить. Если важно, могу разобраться и добавить через пакет

2021-06-18 12:23 UTC, dkrutskikh commented on examples/simple_messenger/analysis_options.yaml
> +# Customizing static analysis
конечно важно - надо понимать где проблема

2021-06-21 08:58 UTC, trushchinskii-surf commented on examples/simple_messenger/lib/data/message.dart
> +  factory Message.fromMap(Map<String, dynamic> map) => Message(
dynamic зло. Убирай их сразу. Заменяй на Object

2021-06-21 08:58 UTC, trushchinskii-surf commented on examples/simple_messenger/lib/data/message.dart
> +  Map<String, dynamic> toMap() => <String, dynamic>{
+

2021-06-21 08:58 UTC, trushchinskii-surf commented on examples/simple_messenger/lib/data/message.dart
> +        sender: map['sender'] as String? ?? '',
Ключи вынеси в константы

2021-06-21 08:58 UTC, trushchinskii-surf commented on examples/simple_messenger/lib/interactor/message/repository/message_repository.dart
> +  const MessageRepository(FirebaseFirestore source) : _source = source;
Тут можно через this.source

2021-06-21 08:58 UTC, trushchinskii-surf commented on examples/simple_messenger/lib/interactor/message/repository/message_repository.dart
> +      _source.collection('messages').add(message.toMap());
Вынеси messages в константу и используй ее во всем файле

2021-06-21 08:58 UTC, trushchinskii-surf commented on examples/simple_messenger/lib/interactor/message/repository/message_repository.dart
> +      .orderBy('timestamp')
Этот ключ надо подтянуть из модельки. Чтобы указывать название единожды

2021-06-21 08:58 UTC, trushchinskii-surf commented on examples/simple_messenger/lib/interactor/message/repository/message_repository.dart
> +    QuerySnapshot<Map<String, dynamic>> snapshot,
dynamic -> Object

2021-06-21 09:14 UTC, plastb1r commented on examples/simple_messenger/lib/interactor/message/repository/message_repository.dart
> +  const MessageRepository(FirebaseFirestore source) : _source = source;
А это нормально, что мы делаем  source открытым? Вроде он не важен для интерфейса этого класса

2021-06-21 14:32 UTC, plastb1r commented on examples/simple_messenger/lib/interactor/message/repository/message_repository.dart
> +    QuerySnapshot<Map<String, dynamic>> snapshot,
+

2021-06-21 14:34 UTC, trushchinskii-surf commented on examples/simple_messenger/lib/interactor/message/repository/message_repository.dart
> +  const MessageRepository(FirebaseFirestore source) : _source = source;
Он не будет открытым. Просто не будет лишних присваиваний

2021-06-21 14:57 UTC, IlyaMax commented on examples/simple_messenger/lib/ui/screens/global_chat/global_chat_screen.dart
> +  Widget _messageListBuilder(BuildContext context, List<Message>? messages) {
у тебя тут уже не нуллабл, можно убрать

2021-06-21 15:11 UTC, plastb1r commented on examples/simple_messenger/lib/ui/screens/global_chat/global_chat_screen.dart
> +  Widget _messageListBuilder(BuildContext context, List<Message>? messages) {
точно, убрал

2021-06-22 07:28 UTC, plastb1r commented on examples/simple_messenger/pubspec.yaml
> +  relation: ^4.0.0-dev.1
заменил

2021-06-22 07:28 UTC, plastb1r commented on examples/simple_messenger/analysis_options.yaml
> +# Customizing static analysis
разобрался и добавил наш линтер

2021-06-23 07:35 UTC, dkrutskikh approved these changes

2021-06-23 07:35 UTC, dkrutskikh commented on examples/simple_messenger/analysis_options.yaml
> +include: package:surf_lint_rules/analysis_options.yaml
@plastb1r не забываем про перенос

2021-06-23 07:47 UTC, plastb1r commented on examples/simple_messenger/analysis_options.yaml
> +include: package:surf_lint_rules/analysis_options.yaml
@dkrutskikh глупый вопрос, но все же, переносим даже когда одна строка(один include)? На всякий посмотрел в surf_lint_rules, там одной строкой добавляют

2021-06-25 07:30 UTC, IlyaMax approved these changes

2021-06-29 09:40 UTC, merged