add possibility to add null content to entity streamed state
surfstudio/SurfGear pull request #257
Opened 2021-06-19 10:50 UTC by IlyaMax

2021-06-19 11:51 UTC, dkrutskikh requested changes

2021-06-19 11:51 UTC, dkrutskikh commented on packages/relation/test/action/states/entity_streamed_state_test.dart
> +        result.map((state) => state.data).toList(),
@IlyaMax `toList` is redundant in this case

2021-06-19 11:51 UTC, dkrutskikh commented on packages/relation/test/action/states/entity_streamed_state_test.dart
> +        result.map((state) => state.data).toList(),
@IlyaMax and this one too

2021-06-19 12:13 UTC, IlyaMax commented on packages/relation/test/action/states/entity_streamed_state_test.dart
> +        result.map((state) => state.data).toList(),
+

2021-06-19 12:13 UTC, IlyaMax commented on packages/relation/test/action/states/entity_streamed_state_test.dart
> +        result.map((state) => state.data).toList(),
+

2021-06-19 12:15 UTC, dkrutskikh approved these changes

2021-06-21 08:37 UTC, trushchinskii-surf approved these changes

2021-06-21 09:11 UTC, IlyaMax commented
decided not to add this because we need from EntityStateBuilder to have contentBuilder with not nullable data. And no other builders should be called if isLoading and isError are false.

2021-06-21 09:11 UTC, closed without merging