SPO-6132 Migrate lint rules
surfstudio/SurfGear pull request #268
Opened 2021-06-30 14:30 UTC by Konoshenko

Remove pedantic dependency. Add flutter_lints rules

2021-06-30 15:07 UTC, dkrutskikh requested changes

2021-06-30 15:07 UTC, dkrutskikh commented on packages/surf_lint_rules/lib/surf_lint_rules.dart
> +void unawaited(Future<void>? future) {}
@Konoshenko перенос строки

2021-06-30 15:44 UTC, Konoshenko commented on packages/surf_lint_rules/lib/surf_lint_rules.dart
> +void unawaited(Future<void>? future) {}
Добавил

2021-06-30 17:09 UTC, dkrutskikh requested changes

2021-06-30 17:25 UTC, Konoshenko commented on packages/surf_lint_rules/CHANGELOG.md
> +## PATCH
Поправил

2021-06-30 17:26 UTC, dkrutskikh approved these changes

2021-07-01 08:39 UTC, MbIXjkee approved these changes
lgtm

2021-07-01 08:40 UTC, merged