Spo 6950 weather logic
surfstudio/SurfGear pull request #310
Opened 2021-08-03 17:18 UTC by zalhonan

Working weather screen - design, logic, service, simple error handler.

2021-08-04 08:39 UTC, artem-zaitsev requested changes

2021-08-04 08:39 UTC, artem-zaitsev commented on examples/weather/lib/modules/weather/services/find_lication.dart
> +Future<LocationData> findLoacation() async {
почему это просто глобальная функция,а не класс?

2021-08-04 08:39 UTC, artem-zaitsev commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/weather_screen.dart
> +  Widget build(BuildContext context) {
надо разбить на отдельные виджеты. Не очень для производительности иметь доинный единый билд метод

2021-08-04 08:39 UTC, artem-zaitsev commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/weather_screen_wm.dart
> +  void setBackround(String newBackground) {
Сделать приватным

2021-08-04 08:39 UTC, artem-zaitsev commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/weather_screen_wm.dart
> +  // }
Это удалить

2021-08-04 08:39 UTC, artem-zaitsev commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/weather_screen_wm.dart
> +    // await Future.delayed(Duration(seconds: 3));
удалить

2021-08-04 08:39 UTC, artem-zaitsev commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/widgets/wather_view_error.dart
> +      {Key? key, required this.inputPadding, required this.dividerPadding})
trailing comma

2021-08-04 10:02 UTC, zalhonan commented on examples/weather/lib/domain/city_model.dart
> +class cityModel {
fixed

2021-08-04 10:13 UTC, zalhonan commented on examples/weather/lib/error_handlers/app_error_handler.dart
> +class AppErrorHandler implements ErrorHandler {
Добавил описания в основные классы

2021-08-04 10:13 UTC, zalhonan commented on examples/weather/lib/modules/weather/repository/weather_repository.dart
> +      throw Exception('Bad request with code:  ${response.statusCode}');
Done

2021-08-04 10:14 UTC, zalhonan commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/weather_screen_wm.dart
> +  void setBackround(String newBackground) {
Done

2021-08-04 10:14 UTC, zalhonan commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/weather_screen_wm.dart
> +  // }
Done

2021-08-04 10:14 UTC, zalhonan commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/weather_screen_wm.dart
> +    // await Future.delayed(Duration(seconds: 3));
Done

2021-08-04 10:15 UTC, zalhonan commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/widgets/wather_view_error.dart
> +      {Key? key, required this.inputPadding, required this.dividerPadding})
done

2021-08-04 12:34 UTC, zalhonan commented on examples/weather/lib/modules/weather/services/find_lication.dart
> +Future<LocationData> findLoacation() async {
исправлено на класс.

2021-08-04 12:49 UTC, zalhonan commented on examples/weather/lib/modules/weather/ui/screens/weather_screen/weather_screen.dart
> +  Widget build(BuildContext context) {
Вынес отдельно SearchBar - три виджета в Row, две иконки и строка поиска.
Остался контейнер с фоном, обернутый в StreamedStateBuilder и EntityStateBuilder, выдающий разные экраны состояний.
Мне кажется, дальше дробить уже будет неудобно.

2021-08-05 08:22 UTC, artem-zaitsev approved these changes

2021-08-05 08:23 UTC, artem-zaitsev approved these changes

2021-08-05 08:33 UTC, merged