SPO-7612 Создан каркас приложения, главный экран
surfstudio/SurfGear pull request #328
Opened 2021-08-30 11:50 UTC by UnusovOleg

2021-08-30 12:03 UTC, artem-zaitsev requested changes

2021-08-30 12:03 UTC, artem-zaitsev commented on examples/my_anime/test/api_test.dart
> +  test('test getting anime', () async {
Что тестирует этот тест?

2021-08-31 05:18 UTC, UnusovOleg commented on examples/my_anime/test/api_test.dart
> +  test('test getting anime', () async {
я его случайно запушил, он чисто для меня нужен, я там брэйкпоинты ставлю и смотрю что мне пришло

2021-08-31 05:18 UTC, UnusovOleg commented on examples/my_anime/lib/ui/screens/main_screen/main_screen.dart
> +  static List<Widget> _screens = <Widget>[
да, конечно

2021-08-31 05:18 UTC, UnusovOleg commented on examples/my_anime/lib/ui/screens/main_screen/main_screen.dart
> +          bottomNavigationBar: BottomNavigationBar(
понял

2021-08-31 11:38 UTC, artem-zaitsev requested changes

2021-08-31 11:38 UTC, artem-zaitsev commented on examples/my_anime/lib/ui/screens/main_screen/main_screen.dart
> +  Widget build(BuildContext context) => StreamedStateBuilder<int>(
Ты не стал пропихивать стрим билдер вовнутрь скаффолда?

2021-08-31 11:38 UTC, artem-zaitsev commented on examples/my_anime/test/api_test.dart
> +void main() {
ты не удалил тест?

2021-08-31 12:07 UTC, UnusovOleg commented on examples/my_anime/lib/ui/screens/main_screen/main_screen.dart
> +  Widget build(BuildContext context) => StreamedStateBuilder<int>(
я оставил так, сейчас переписываю с использование tabnavigator

2021-08-31 12:07 UTC, UnusovOleg commented on examples/my_anime/test/api_test.dart
> +void main() {
понял, удалю

2021-08-31 12:38 UTC, merged