flt-509-messenger_refactor
surfstudio/SurfGear pull request #34
Opened 2020-12-03 10:58 UTC by vlad-bel

добавил material_app_message_controller.dart работающий на ScaffoldMessenger

2020-12-03 18:08 UTC, saturov requested changes

2020-12-03 18:08 UTC, saturov commented on template/lib/ui/base/material_app_message_controller.dart
> +    Logger.d(' SnackBar is nul? ${snack == null} by type = $msgType');
да и сам лог какой-то мутный, непонятный. переписать его надо

2020-12-08 11:02 UTC, vlad-bel commented on template/lib/ui/base/material_app_message_controller.dart
> +  /// Дефолтные снеки, используются если виджет не определил свои
поправил

2020-12-08 11:02 UTC, vlad-bel commented on template/lib/ui/base/material_app_message_controller.dart
> +    Logger.d(' SnackBar is nul? ${snack == null} by type = $msgType');
выпилил мутные логи

2021-01-12 07:57 UTC, saturov approved these changes

2021-01-12 08:28 UTC, artem-zaitsev approved these changes

2021-01-12 08:28 UTC, merged