Spo 8083 mwwm new example
surfstudio/SurfGear pull request #348
Opened 2021-09-15 09:24 UTC by Graaggas

Пример на mwwm. C https://jsonplaceholder.typicode.com тянется список пользователей, на экране при нажатии на floatingactionbutton рандомным образом отображается имя из списка пользователей.

2021-09-16 07:39 UTC, dkrutskikh requested changes

2021-09-16 07:39 UTC, dkrutskikh commented on examples/users/web/index.html
> +<!DOCTYPE html>
@Graaggas давай уберем папку web

2021-09-16 07:39 UTC, dkrutskikh commented on examples/users/test/widget_test.dart
> +// This is a basic Flutter widget test.
@Graaggas и заглушечный пустой тест

2021-09-16 07:39 UTC, dkrutskikh commented on examples/users/pubspec.yaml
> +name: example2
@Graaggas давай подчистим пабспек

2021-09-16 09:58 UTC, Graaggas commented on examples/users/analysis_options.yaml
> +include: package:flutter_lints/flutter.yaml
готово

2021-09-16 09:58 UTC, Graaggas commented on examples/users/README.md
> +# example2
готово

2021-09-16 09:58 UTC, Graaggas commented on examples/users/web/index.html
> +<!DOCTYPE html>
готово

2021-09-16 09:58 UTC, Graaggas commented on examples/users/test/widget_test.dart
> +// This is a basic Flutter widget test.
готово

2021-09-16 09:58 UTC, Graaggas commented on examples/users/pubspec.yaml
> +name: example2
готово

2021-09-23 08:00 UTC, MbIXjkee commented
Давайте сразу пернесем из surfgear в mwwm пакет

2021-10-05 15:13 UTC, closed without merging