FLT-489 remove deprecated method
surfstudio/SurfGear pull request #43
Opened 2020-12-22 10:47 UTC by pretorean

2020-12-23 15:13 UTC, artem-zaitsev requested changes

2020-12-23 15:13 UTC, artem-zaitsev commented on packages/surf_injector/lib/src/surf_injector.dart
> +    final injector = context.getElementForInheritedWidgetOfExactType<_Injector<C>>()?.widget;
там была логика, что он сначала ищет Injector<C>, а потом Injector - не потерял?

2020-12-23 15:13 UTC, artem-zaitsev commented on packages/surf_injector/lib/src/surf_injector.dart
> +    // does not have its own state, does not react to changing dependencies,
шик

2020-12-23 15:44 UTC, pretorean commented on packages/surf_injector/lib/src/surf_injector.dart
> +    final injector = context.getElementForInheritedWidgetOfExactType<_Injector<C>>()?.widget;
он ищет _Injector<C>, это там компонент нужного типа, если его нет чем нам поможет просто _Injector ?
Либо я чтото не понимаю?

2020-12-24 08:51 UTC, artem-zaitsev commented on packages/surf_injector/lib/src/surf_injector.dart
> +    final injector = context.getElementForInheritedWidgetOfExactType<_Injector<C>>()?.widget;
Он найдет любой инжектор и попытается вытянуть из него. На самом деле, может оно и не надо

2021-01-12 08:30 UTC, merged