Relation readme improvements
surfstudio/SurfGear pull request #47
Opened 2020-12-25 06:51 UTC by saturov

2021-01-17 21:17 UTC, AnPech requested changes

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +The **Relation** package provides you not only some basic components for common use-cases, but even more highly specialized classes for solving specific problems.
The **Relation** package provides you not only with some basic components for common use cases, but with even more highly specialized classes for solving different issues.

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +`TextEditingAction` is the special type of **Action** to track the text changes in the text field. The built-in `TextEditingController` makes it possible.
`TextEditingAction` is a special type of **Action** that tracks text changes in the text field. The built-in `TextEditingController` makes it possible.

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +`ControllerAction` is more common than two previous variations. During the `ControllerAction` instantiation you can pass a [`ValueNotifier`](https://api.flutter.dev/flutter/foundation/ValueNotifier-c
`ControllerAction` is more common than the two previous variations. You can pass a [`ValueNotifier`] during the `ControllerAction` instantiation.

Мне опять не оч нравится pass, какой здесь по-русски глагол?

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +This means that you can work with the `ClipboardStatusNotifier`, `TextEditingController` or `TransformationController` through the `ControllerAction`.
This means you can work with the `ClipboardStatusNotifier`, `TextEditingController` or `TransformationController` through the `ControllerAction`.

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +`EntityStreamedState` is an extended version of `StreamedState` designed to make it easier to implement typical dynamic data screens.
`EntityStreamedState` is an extended version of `StreamedState` designed to make implementing typical dynamic data screens easier.

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +We have noticed that most screens in mobile applications are quite simple and have several typical states:
Most screens in mobile applications are quite simple and usually have several typical states:

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +`EntityStreamedState` provides you a handy interface for the data stream to handle these states properly.
`EntityStreamedState` provides you with a convenient interface for the data stream to handle these states properly.

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +Create a `EntityStreamedState` class instance. Actually, it has the same abilities as `StreamedState`: the initial value setup and the specific data type declaration. Notice that `EntityStreamedState
Create a `EntityStreamedState` class instance. It has the same abilities as `StreamedState`: the initial value setup and the specific data type declaration. Keep in mind that `EntityStreamedState` accepts an `EntityState` wrapper around your data rather than a raw part of your data.

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +But what all these functions actually do? The answer is on the other side. Using `EntityStateBuilder` instead of simple `StreamedStateBuilder` you can set widgets for all three states in a declarativ
But what do all these functions actually do? The answer is on the other side. By using `EntityStateBuilder` instead of just `StreamedStateBuilder` you can set widgets for all three states and switch between them easily.

in a declarative way  - я бы убрала, если это некритично

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +Pass `EntityStreamedState` instance to the `streamedState` argument first. Right after that you can specify a set of widgets for displaying data (`child`), load state (`loadingChild`) and error state
Pass the `EntityStreamedState` instance to the `streamedState` argument first. After that, you can specify a set of widgets for displaying data (`child`), load state (`loadingChild`), and error state (`errorChild`).

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +The idea of `TextFieldStreamedState` and `TextFieldStateBuilder` technically the same with the difference that `TextFieldStreamedState` is designed to work with text widgets (`Text`, `TextField`, etc
The idea behind `TextFieldStreamedState` and `TextFieldStateBuilder` is technically the same. The only difference is that `TextFieldStreamedState` is designed to work with text widgets (`Text`, `TextField`, etc.).

2021-01-17 21:17 UTC, AnPech commented on packages/relation/README.md
> +`TextFieldStreamedState` allows you to setup your text field validation rules and some other settings like is the text field enabled or mandatory to be filled.
TextFieldStreamedState` allows you to set up your text field validation rules and some other settings, such as making the text field mandatory for the user to fill out.

2021-01-19 07:26 UTC, saturov commented on packages/relation/README.md
> +This solution provides you an ability to call `Action` class from `relation` library without any additional preffixes, but deprives you of the opportunity to reffer *Action* class from the SDK.
Да, ссылаться, обращаться

2021-01-19 07:28 UTC, saturov commented on packages/relation/README.md
> +Find the place where you're going to handle events triggered by your `Action`. Subscribe to the event stream, which you can access through the `stream` property.
Нет, тут смысл был в том, что нужно найти место, где будут обрабатываться экшны, реализована реакция на их срабатывание.

2021-01-19 07:30 UTC, saturov commented on packages/relation/README.md
> +With `StreamedState` you can notify consumers of data changes.
А нам и нужно тут слово в значении "потребитель", это устоявшееся выражение в этом контексте.

2021-01-19 07:32 UTC, saturov commented on packages/relation/README.md
> +Create a `StreamedState` class instance. `StreamedState` constructor allows you to set the initial value that the consumer will receive as soon as it subscribes to the `StreamedState`. You need to sp
Тоже самое насчёт customers и consumer.

2021-01-19 07:32 UTC, saturov commented on packages/relation/README.md
> +To notify all consumers of data changes, you can emit the actual data to the `StreamedState` via the `accept()` function.
Тоже самое насчёт customers и consumers.

2021-01-19 07:43 UTC, saturov commented on packages/relation/README.md
> +`ControllerAction` is more common than two previous variations. During the `ControllerAction` instantiation you can pass a [`ValueNotifier`](https://api.flutter.dev/flutter/foundation/ValueNotifier-c
Передавать в качестве параметра в функцию. Тоже довольно устоявшийся оборот.

2021-01-19 19:56 UTC, AnPech commented on packages/relation/README.md
> +Find the place where you're going to handle events triggered by your `Action`. Subscribe to the event stream, which you can access through the `stream` property.
тогда вот так: Find a place to process events triggered by your Action. Subscribe to the event stream. You can access it through the stream property.

2021-01-19 19:56 UTC, AnPech commented on packages/relation/README.md
> +With `StreamedState` you can notify consumers of data changes.
аааа сорри

With StreamedState you can notify your consumers of any data changes.

2021-01-19 19:57 UTC, AnPech commented on packages/relation/README.md
> +Create a `StreamedState` class instance. `StreamedState` constructor allows you to set the initial value that the consumer will receive as soon as it subscribes to the `StreamedState`. You need to sp
Create a StreamedState class instance. StreamedState constructor allows you to set the initial value that the consumers will receive as soon as they subscribe to the StreamedState. You need to specify the data type that your StreamedState will handle.

2021-01-19 19:57 UTC, AnPech commented on packages/relation/README.md
> +To notify all consumers of data changes, you can emit the actual data to the `StreamedState` via the `accept()` function.
To notify consumers of any data changes, you can release the relevant data to the StreamedState via the accept() function.

2021-01-19 19:58 UTC, AnPech commented on packages/relation/README.md
> +`ControllerAction` is more common than two previous variations. During the `ControllerAction` instantiation you can pass a [`ValueNotifier`](https://api.flutter.dev/flutter/foundation/ValueNotifier-c
Ттгда ок: ControllerAction is more common than the two previous variations. You can pass a [ValueNotifier] during the ControllerAction instantiation.

2021-07-09 13:18 UTC, merged