mwwm null safety
surfstudio/SurfGear pull request #50
Opened 2021-01-12 14:07 UTC by pretorean

2021-01-14 07:40 UTC, artem-zaitsev requested changes

2021-01-14 07:40 UTC, artem-zaitsev commented on packages/mwwm/lib/src/widget_state.dart
> +  WM? _wm;
Скорее late, https://dart.dev/null-safety#creating-variables

2021-01-14 10:36 UTC, pretorean commented on packages/mwwm/lib/src/widget_state.dart
> +  WM? _wm;
исправил

2021-01-18 07:40 UTC, saturov approved these changes

2021-04-13 14:00 UTC, closed without merging