add null safety to relation
surfstudio/SurfGear pull request #51
Opened 2021-01-13 09:37 UTC by pretorean

2021-01-13 12:43 UTC, MbIXjkee commented on packages/relation/example/pubspec.yaml
>    sdk: ">=2.1.0 <3.0.0"
а тут разве не выше должно быть нижнее ограничение

2021-01-13 12:43 UTC, MbIXjkee commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +    Key? key,
А теперь так принято required именованные поднимать на самый верх? вроде key обычно из именованных на 1 место ставили

2021-01-13 13:33 UTC, pretorean commented on packages/relation/example/pubspec.yaml
>    sdk: ">=2.1.0 <3.0.0"
это же example, тут повышение версии ни на что не влияет

2021-01-13 13:34 UTC, pretorean commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +    Key? key,
у линтера есть хинт что required должны быть первыми, а key необязательняй параметр

2021-01-13 13:36 UTC, pretorean commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +    Key? key,
@MbIXjkee посмотри и другие ПР с null safety

2021-01-13 14:05 UTC, pretorean commented on packages/relation/example/pubspec.yaml
>    sdk: ">=2.1.0 <3.0.0"
ты прав, исправил

2021-01-14 07:48 UTC, artem-zaitsev commented on packages/relation/lib/src/relation/action/action.dart
> +class Action<T> implements Event<T?> {
А может ли быть null? Нам надо чтобы в Action(да и в State) мог быть null? 

У меня есть подозрение, что нет. Но интересно еще точки зрения послушать.

2021-01-14 07:48 UTC, artem-zaitsev commented on packages/relation/lib/src/relation/state/entity_state.dart
> +class EntityStreamedState<T> extends StreamedState<EntityState<T>> implements EntityEvent<T> {
Если здесь T - non null то и в Action тоже должен быть.

2021-01-14 08:06 UTC, saturov requested changes

2021-01-14 08:06 UTC, saturov commented on packages/relation/lib/src/relation/action/action.dart
> +class Action<T> implements Event<T?> {
Думаю, что скорее да, чем нет. У нас легко может возникнуть ситуация, когда мы получили от сервера не данные, а ничего, т.е. null. В этом случае мы либо кидаем этот null в State и каким-то заранее определённым образом обрабатываем эту ситуацию на UI, либо же нам придётся в этот момент подменять null на какое-то значение по-умолчанию, олицетворяющее "ничего". Это выглядит усложнением, которое все будут реализовывать по-разному.

2021-01-14 08:06 UTC, saturov commented on packages/relation/example/lib/demo_relations.dart
> +      (_) => incrementState.accept(incrementState.value! + 1),
Тут никак без ! не обойтись?

2021-01-14 08:22 UTC, pretorean commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +            return loadingBuilder!(context, streamData!.data);
в этом месте ! используется чтобы не было хинта линтера, но так как этот код выполняется после проверки на null, то это безопасно

2021-01-14 08:22 UTC, pretorean commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +              streamData.error != null ? streamData.error!.e as Exception : Exception(),
ответил выше

2021-01-14 08:33 UTC, Evoswork commented on packages/relation/lib/src/relation/state/entity_state.dart
> +class EntityStreamedState<T> extends StreamedState<EntityState<T>> implements EntityEvent<T> {
Так же как и Action возможна ситуация, что описал Сатуров. Так же в прошлой версии без null safety, если ассептим null, то автоматом видим состояние ошибки, но это поведение кажется не корректным, у меня не остаётся варианта обработать null как результат

2021-01-14 09:06 UTC, Jokerkras commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +            return loadingBuilder!(context, streamData!.data);
А нужно ли такое правило в линтере, IDE сама скажет где надо про несоответствие int? и int

2021-01-14 09:18 UTC, pretorean commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +            return loadingBuilder!(context, streamData!.data);
я не правильно выразился, ты получаешь ошибку несответствия типов, что Type не есть Type? и ! в этом случае приводит Type? к Type и после проверки на null это безопасно

2021-01-14 09:23 UTC, Jokerkras commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +            return loadingBuilder!(context, streamData!.data);
ааа, просто по идее если делать проверку на null, то внутри then dart должен считать, что переменная уже точно не Type?. Ладно, видел пару раз как у меня не срабатывало похожее

2021-01-14 10:42 UTC, pretorean commented on packages/relation/lib/src/relation/action/action.dart
> +class Action<T> implements Event<T?> {
В этой библиотеке много где используются опциональные параметры, например `Future<void> accept([T data]) {` и опциональный параметр может быть null, если не позволить ему быть null, то тогда потеряется возможность вызвать `accept()` или `loading()` без параметров.
Если значению внутри `StreamState` не позволить быть null, тогда даже объявление `StreamState<Type?>` будет требовать передать параметр в `accept()`

2021-01-14 10:44 UTC, pretorean commented on packages/relation/example/lib/demo_relations.dart
> +      (_) => incrementState.accept(incrementState.value! + 1),
никак, значение внутри стейта `int?`

2021-01-14 11:01 UTC, HazarD2311 commented on packages/relation/lib/src/relation/action/action.dart
> +class Action<T> implements Event<T?> {
Тем самы кажется, что мы вообще не используем во всю null safety. По итогу проверки на null все также дойдут до UI, хотя нужны их отсечь на этапе подготовки данных
имхо

2021-01-14 11:57 UTC, MbIXjkee commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +    Key? key,
Я щас кст спецом посмотрел как в самом flutter делают 
![image](https://user-images.githubusercontent.com/14325911/104588019-d97f6080-5678-11eb-9345-bf3d221cf1cc.png)

2021-01-14 12:33 UTC, pretorean commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +    Key? key,
у нас есть always_put_required_named_parameters_first

2021-01-18 07:45 UTC, saturov commented on packages/relation/lib/src/relation/action/action.dart
> +class Action<T> implements Event<T?> {
На самом деле используем. Так как появление null safety в языке не равнозначно тому, что `Null` отныне использовать вообще запрещено. Скорее это фича, которая помогает нам подчеркнуть те места, где `Null` может появиться, а значит нам следует такую ситуацию обработать.

2021-01-18 07:51 UTC, saturov commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +            return loadingBuilder!(context, streamData!.data);
Да вот и я тоже думал, что это после проверки анализатор уже понимает, что переменная не null. Так не работает? @pretorean

2021-01-18 07:51 UTC, saturov commented on packages/relation/example/lib/demo_relations.dart
> +      (_) => incrementState.accept(incrementState.value! + 1),
Ну так а если вдруг так случится, что там будет Null?

2021-01-18 07:53 UTC, saturov commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +    Key? key,
Мне кажется это имеет смысл. Это логично и удобно.

2021-01-18 07:55 UTC, saturov commented on packages/relation/lib/src/relation/action/action.dart
> +class Action<T> implements Event<T?> {
На самом деле используем. Так как появление null safety в языке не равнозначно тому, что `Null` отныне использовать вообще запрещено. Скорее это фича, которая помогает нам подчеркнуть те места, где `Null` может появиться, а значит нам следует такую ситуацию обработать.

2021-01-18 08:24 UTC, pretorean commented on packages/relation/lib/src/builder/entity_stream_builder.dart
> +            return loadingBuilder!(context, streamData!.data);
Ну это же не магия. После проверки на null тип переменной остается `Type?` и для приведения типа к `Type` используется оператор !

2021-04-13 08:05 UTC, closed without merging