add null safety to surf_mwwm
surfstudio/SurfGear pull request #53
Opened 2021-01-13 13:56 UTC by pretorean

перед сливанием исправить версии пакетов surf_injector, relation, mwwm в pubspec на версии с поддержкой null safety

2021-01-18 07:57 UTC, saturov requested changes

2021-01-18 07:57 UTC, saturov commented on packages/surf_mwwm/example/lib/ui/screen/counter/counter_wm.dart
> +      (_) => counterState.accept(counterState.value! + 1),
Аналогичный вопрос тому, который был в mwwm-пакете.
А если тут вдруг всплывёт Null?

2021-01-18 07:57 UTC, saturov commented on packages/surf_mwwm/example/lib/ui/screen/counter/counter_wm.dart
> +      counterState.stream.where((c) => c!.isEven).skip(1),
И тут тоже самое.

2021-01-18 07:57 UTC, saturov commented on packages/surf_mwwm/pubspec.yaml
> +      ref: feature/mwwm_null_safety
Это же после того, как пакеты будут слиты в dev - заменить придётся? Надо оставить todo. И не забыть об этом.

2021-01-18 08:18 UTC, pretorean commented on packages/surf_mwwm/example/lib/ui/screen/counter/counter_wm.dart
> +      (_) => counterState.accept(counterState.value! + 1),
По реализации в relation `StreamState<Type>` отдает `StreamState.value` с типом `Type?`. И по хорошему нужно везде делать проверку на null, но если не ложить в этот state null, как в этом примере, то к значению можно обращаться через ! чтобы немного сократить код.

2021-01-18 08:19 UTC, pretorean commented on packages/surf_mwwm/example/lib/ui/screen/counter/counter_wm.dart
> +      counterState.stream.where((c) => c!.isEven).skip(1),
https://github.com/surfstudio/SurfGear/pull/53#discussion_r559383527

2021-01-18 09:20 UTC, pretorean commented on packages/surf_mwwm/pubspec.yaml
> +      ref: feature/mwwm_null_safety
я в описании ПР про это написал

2021-04-22 14:58 UTC, artem-zaitsev requested changes

2021-04-22 14:58 UTC, artem-zaitsev commented on packages/surf_mwwm/pubspec.yaml
> +  # mwwm: ^1.0.3
не забудь убрать

2021-04-22 14:58 UTC, artem-zaitsev commented on packages/mwwm/CHANGELOG.md
> +## 1.0.3
1.1.0

2021-04-22 15:19 UTC, artem-zaitsev approved these changes

2021-04-22 15:19 UTC, artem-zaitsev commented on packages/surf_mwwm/lib/src/extensions/mwwm_extensions.dart
> +    required void Function(dynamic e) onError,
не required

2021-04-26 11:47 UTC, grafovdenis commented
### Summary

1. `SurfMwwmExtension` bind - ok
2. `FutureExt` `on` - ok
3. `FutureExt` `on` with error - ok
4. `FutureExt` `withErrorHandling` - ok
5. `EntityExt` `map` - fails when we accept something to source stream.
Reason: `StreamedState.from`
6. `EventExt` `map` - same as 5.
7. `EventExt` `doOnData`, `doEventOnData` - fails couse we don't subscribe to stream.
8. `EventExt` `bind` - ok.
9. `EventExt` `listenOn`, `listenCathError` - fails with error callback.
10. `StreamX` - ok.
11. `InjectorExt` - ok.

2021-04-27 07:12 UTC, dkrutskikh approved these changes

2021-04-27 07:15 UTC, merged