add null safety to tabnavigator
surfstudio/SurfGear pull request #60
Opened 2021-01-15 13:37 UTC by pretorean

изменить ссылки на зависимости:

2021-01-18 12:23 UTC, saturov approved these changes

2021-04-27 09:40 UTC, grafovdenis commented on packages/tabnavigator/lib/src/tab_navigator.dart
> -        if (snapshot.connectionState != ConnectionState.active) {
This check removed since we pass initial data.

2021-04-27 13:54 UTC, dkrutskikh approved these changes

2021-04-27 14:02 UTC, Jokerkras approved these changes

2021-04-27 14:29 UTC, artem-zaitsev requested changes

2021-04-27 14:29 UTC, artem-zaitsev commented on packages/tabnavigator/lib/src/tab_navigator.dart
> +  Future<bool> _isCanWillPop(TabType tabType) async {
давай в _willPop переименуем

2021-04-27 14:29 UTC, artem-zaitsev commented on packages/tabnavigator/test/tab_navigator_test.dart
> +    testWidgets('smoke test', (tester) async {
тут без экспект?

2021-04-27 17:17 UTC, grafovdenis commented on packages/tabnavigator/test/tab_navigator_test.dart
> +    testWidgets('smoke test', (tester) async {
Да, как [тут](https://github.com/surfstudio/SurfGear/blob/dev/packages/bottom_sheet/test/bottom_sheet_test.dart#L38)
Просто проверка на то, что ничего не упало

2021-04-27 17:23 UTC, merged