no-task - Изменение очередности объявления структуры класса
surfstudio/SurfGear pull request #82
Opened 2021-02-20 08:27 UTC by trushchinskii-surf

2021-02-25 10:23 UTC, HazarD2311 approved these changes

2021-02-25 10:39 UTC, pretorean approved these changes

2021-02-26 08:57 UTC, Jokerkras approved these changes

2021-02-26 09:02 UTC, knightsforce commented on docs/ru/common/code_style.md
> +1. Публичные static методы
В полях смешаны приватные и публичные, разграниченные по static / final и т.д.
А методы разграничены по публичности / приватности.

Где последовательность?

2021-02-26 09:31 UTC, AndX2 commented on docs/ru/common/code_style.md
> +1. Именованные конрструкторы класса
Есть ишью для анализатора:
Для классов-компонентов удобно поля, получаемые при инициализации поднять выше конструктора / фабрики конструктора.
Предлагаю добавить правило анализатора, что если имя класса содержит Interactor|Service|Register|Client|Model|Repository - тогда его на порядок расположения конструктора не агрим.

2021-02-26 10:17 UTC, HazarD2311 commented on docs/ru/common/code_style.md
> +1. Именованные конрструкторы класса
кстати хорошее замечение. В WM всегда в вверху хочется зависимости видеть сначала

2021-02-26 12:54 UTC, trushchinskii-surf commented on docs/ru/common/code_style.md
> +1. Именованные конрструкторы класса
Ну хз. Расплывется мне кажется. Или правило написания есть, или его нет. Зачем для один сущностей одну стилистику кода делать, для других другую.

2021-02-26 16:50 UTC, AndX2 commented on docs/ru/common/code_style.md
> +1. Именованные конрструкторы класса
Code style служит цели повышения читабельности. Если его правило, в данном случае, снижает читабельность - это неправильный code style.
Хорошим примером использования степеней в правилах может быть ЕСКД:
<условно>
1. Конструкторы и фабрики располагаются в начале класса до объявления полей
2. ДОПУСКАЕТСЯ размещать final поля, получаемые при инициализации экземпляра класса, до объявления конструктора.

2021-03-01 08:18 UTC, trushchinskii-surf commented on docs/ru/common/code_style.md
> +1. Публичные static методы
Не понял что ты имеешь ввиду?

2021-03-10 08:19 UTC, artem-zaitsev requested changes

2021-03-10 08:19 UTC, artem-zaitsev commented on docs/ru/common/code_style.md
> +1. Именованные конрструкторы класса
@trushchinskii что решили?

2021-03-12 07:42 UTC, trushchinskii-surf commented on docs/ru/common/code_style.md
> +1. Именованные конрструкторы класса
Перенес конструкторы ниже полей.

2021-03-15 07:40 UTC, artem-zaitsev approved these changes
Сливай и скажи, что у нас обновления в кодстайле в чат.
@trushchinskii-surf ]

2021-04-02 11:01 UTC, merged