no-task - исправление лишнего вызова onRefresh
surfstudio/SurfGear pull request #85
Opened 2021-03-01 09:14 UTC by arefimenko

баг был найден при [исправлении бага на ios](https://github.com/surfstudio/labelcom-flutter/pull/818)

2021-03-01 09:15 UTC, Jokerkras approved these changes

2021-03-01 14:05 UTC, artem-zaitsev approved these changes

2021-03-01 14:06 UTC, artem-zaitsev commented
@arefimenko    Нужна запись в ченжлог

2021-03-03 13:40 UTC, artem-zaitsev requested changes

2021-03-03 13:40 UTC, artem-zaitsev commented on packages/swipe_refresh/pubspec.yaml
> +version: "0.0.1-dev.12"
здесь отмени изменение. Это автоматом произойдет.
В ченжлог ставим будущее версию(т.е то что в пабспеке + 1)

2021-03-03 13:49 UTC, arefimenko commented on packages/swipe_refresh/pubspec.yaml
> +version: "0.0.1-dev.12"
+

2021-03-10 08:19 UTC, artem-zaitsev approved these changes

2021-03-10 08:19 UTC, merged