FLT-1228 - counter example mwwm package
surfstudio/SurfGear pull request #86
Opened 2021-03-01 12:35 UTC by arefimenko

2021-03-02 09:45 UTC, artem-zaitsev requested changes
Поправь мелочи

2021-03-02 09:45 UTC, artem-zaitsev commented on packages/mwwm/example/counter/lib/main.dart
> +class _DefaultErrorHandler implements ErrorHandler {
Положи этот класс в соответствующую папку. Лучше в слой UI

2021-03-02 09:45 UTC, artem-zaitsev commented on packages/mwwm/example/counter/lib/ui/counter_screen/counter_route.dart
> +WidgetModel _widgetModelDependencies(BuildContext context) {
Это builder. Лучше назват createCounterWm

2021-03-02 09:45 UTC, artem-zaitsev commented on packages/mwwm/example/counter/lib/ui/counter_screen/counter_route.dart
> +WidgetModel _widgetModelDependencies(BuildContext context) {
Мы стараемся называть методы с глаголов

2021-03-02 09:45 UTC, artem-zaitsev commented on packages/mwwm/example/counter/lib/ui/counter_screen/counter_wm.dart
> +// ignore: prefer_mixin
А чет там за правило с миксинами?

2021-03-02 09:51 UTC, arefimenko commented on packages/mwwm/example/counter/lib/ui/counter_screen/counter_wm.dart
> +// ignore: prefer_mixin
[правило](https://dart-lang.github.io/linter/lints/prefer_mixin.html), то что ChangeNotifier класс ему не нравится

2021-03-03 13:46 UTC, artem-zaitsev approved these changes

2021-03-03 13:47 UTC, merged