FLT-1230 - surf_controllers package
surfstudio/SurfGear pull request #88
Opened 2021-03-02 09:24 UTC by arefimenko

2021-03-02 09:47 UTC, artem-zaitsev requested changes
И где example?

2021-03-02 09:47 UTC, artem-zaitsev commented on packages/surf_controllers/lib/surf_controllers.dart
> +part 'src/dialog_controller.dart';
Почему не export?

2021-03-02 13:30 UTC, arefimenko commented on packages/surf_controllers/lib/surf_controllers.dart
> +part 'src/dialog_controller.dart';
через `part` в root файле можно импортить нужные зависимости для остальных файлов, в которых указывать лишь `part of *library_name*`, поможет избавиться от лишнего количества импортов в файлах в `src` директории

2021-03-03 13:48 UTC, artem-zaitsev commented on packages/surf_controllers/lib/surf_controllers.dart
> +part 'src/dialog_controller.dart';
А ты без export разве сможешь их наружу прокинуть?

2021-03-03 13:52 UTC, arefimenko commented on packages/surf_controllers/lib/surf_controllers.dart
> +part 'src/dialog_controller.dart';
да, то что является part of библиотеки, автоматом становится export, можем добавить экспорт на что то другое, что мы используем внутри пакета

2021-03-03 13:55 UTC, artem-zaitsev requested changes

2021-03-03 13:55 UTC, artem-zaitsev commented on packages/surf_controllers/lib/surf_controllers.dart
> +part 'src/dialog_controller.dart';
увидел

2021-03-03 13:55 UTC, artem-zaitsev commented on packages/surf_controllers/lib/surf_controllers.dart
> +part 'src/dialog_controller.dart';
Вообще, не видел раньше чтобы наружу провайдил через part.
Это не совсем состыкуется с общей конвенцией и рекомендациями: https://dart.dev/guides/libraries/create-library-packages

И таким образом видно все содержимое part.

Проверь - насколько это все видно извне.

2021-03-03 14:17 UTC, arefimenko commented
![image](https://user-images.githubusercontent.com/54911543/109818654-45775180-7c44-11eb-9ca7-205e0c3dc342.png)
граничить доступ можно, но тогда приходится "извращаться" так скажем, с export попроще будет в разы

2021-03-03 14:22 UTC, arefimenko commented on packages/surf_controllers/lib/surf_controllers.dart
> +part 'src/dialog_controller.dart';
то что мы выносим в `part`/`part of` автоматом становится частью библиотеки, просто разбитым на несколько файлов и доступ есть ко всему

2021-03-10 08:22 UTC, merged