FLT-1248 - Доработка код стайла для dart
surfstudio/SurfGear pull request #89
Opened 2021-03-05 12:14 UTC by trushchinskii-surf

2021-03-05 12:44 UTC, dkrutskikh approved these changes

2021-03-07 10:35 UTC, artem-zaitsev commented on docs/ru/common/code_style.md
> +Dart позволяет хранить в одном файле несколько классов, однако это ухудшает читаемость кода и делает
У общем, по поводу объединения - это крайне неочевидная штука.

Приватные виджеты удобно делать внутри файла экрана.

Вынесите на общий

2021-03-09 05:12 UTC, trushchinskii-surf commented on docs/ru/common/code_style.md
> +Dart позволяет хранить в одном файле несколько классов, однако это ухудшает читаемость кода и делает
Приватные да, поэтому написал не рекомендуется. Можно дописать заисключением ui-приватных классов
Что значит вынесите на общий?

2021-03-09 07:08 UTC, artem-zaitsev commented on docs/ru/common/code_style.md
> +Dart позволяет хранить в одном файле несколько классов, однако это ухудшает читаемость кода и делает
Да, напиши, пожалуйста про виджеты, что это исключение.

По поводу "на общий" - имел ввиду на общее обсуждение. Но уже не требуется.

Правда требуется довести обновление до всех

2021-03-10 07:55 UTC, artem-zaitsev requested changes

2021-03-10 07:55 UTC, artem-zaitsev commented on docs/ru/common/code_style.md
> +Dart позволяет хранить в одном файле несколько классов, однако это ухудшает читаемость кода и делает
@trushchinskii Напишешь про исключение?

2021-03-12 07:49 UTC, trushchinskii-surf commented on docs/ru/common/code_style.md
> +Dart позволяет хранить в одном файле несколько классов, однако это ухудшает читаемость кода и делает
Поправил

2021-03-15 07:41 UTC, artem-zaitsev approved these changes

2021-03-15 07:41 UTC, artem-zaitsev commented on docs/ru/common/code_style.md
> +<!-- markdownlint-disable MD041 -->
а что это за интересная штука?

2021-03-18 06:22 UTC, trushchinskii-surf commented on docs/ru/common/code_style.md
> +<!-- markdownlint-disable MD041 -->
Это сделано для проверки форматирования md файлов. У них первым должен идти хедер 1. ПОэтому чтобы не ругался это написал

2021-04-02 11:47 UTC, merged